// src/context/dateInputActionTypes.js
export const SET_YEAR = 'SET_YEAR';
export const SET_MONTH = 'SET_MONTH';
export const SET_DAY = 'SET_DAY';
export const SET_DATE = 'SET_DATE';

export const SET_GENERAL_DATE_ERROR = 'SET_GENERAL_DATE_ERROR';
export const SET_YEAR_ERROR = 'SET_YEAR_ERROR';
export const SET_MONTH_ERROR = 'SET_MONTH_ERROR';
export const SET_DAY_ERROR = 'SET_DAY_ERROR';
export const SET_DATE_ERROR = 'SET_DATE_ERROR';
export const CLEAR_DATE_ERROR = 'CLEAR_DATE_ERROR';

export const SET_YEAR_NULL_ERROR = 'SET_YEAR_NULL_ERROR';
export const SET_MONTH_NULL_ERROR = 'SET_MONTH_NULL_ERROR';
export const SET_DAY_NULL_ERROR = 'SET_DAY_NULL_ERROR';
export const CLEAR_YEAR_NULL_ERROR = 'CLEAR_YEAR_NULL_ERROR';
export const CLEAR_MONTH_NULL_ERROR = 'CLEAR_MONTH_NULL_ERROR';
export const CLEAR_DAY_NULL_ERROR = 'CLEAR_DAY_NULL_ERROR';
export const CLEAR_DATE_NULL_ERROR = 'CLEAR_DATE_NULL_ERROR';

export const SET_FLAG = 'SET_FLAG';
export const SET_CAL = 'SET_CAL';

export const SET_DISABLED_MONTHS = 'SET_DISABLED_MONTHS';
export const SET_LAST_DAY = 'SET_LAST_DAY';

export const SET_DATE_ADJUSTING_ON = 'SET_DATE_ADJUSTING_ON';
export const SET_DATE_ADJUSTING_OFF = 'SET_DATE_ADJUSTING_OFF';

export const SET_DATE_FETCHING_ON = 'SET_DATE_FETCHING_ON';
export const SET_DATE_FETCHING_OFF = 'SET_DATE_FETCHING_OFF';

export const SET_DATE_VALID = 'SET_DATE_VALID';
