// src/context/locationInputActionTypes.js
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_LAT = 'SET_LAT';
export const SET_LNG = 'SET_LNG';
export const SET_ID = 'SET_ID';
export const SET_TZ = 'SET_TZ';
export const SET_LOCATION = 'SET_LOCATION';
export const CLEAR_LOCATION = 'CLEAR_LOCATION';

export const SET_ADDRESS_ERROR = 'SET_ADDRESS_ERROR';
export const SET_LAT_ERROR = 'SET_LAT_ERROR';
export const SET_LNG_ERROR = 'SET_LNG_ERROR';
export const SET_LOCATION_ERROR = 'SET_LOCATION_ERROR';
export const CLEAR_LOCATION_ERROR = 'CLEAR_LOCATION_ERROR';

export const SET_ADDRESS_NULL_ERROR = 'SET_ADDRESS_NULL_ERROR';
export const SET_LAT_NULL_ERROR = 'SET_LAT_NULL_ERROR';
export const SET_LNG_NULL_ERROR = 'SET_LNG_NULL_ERROR';
export const CLEAR_ADDRESS_NULL_ERROR = 'CLEAR_ADDRESS_NULL_ERROR';
export const CLEAR_LAT_NULL_ERROR = 'CLEAR_LAT_NULL_ERROR';
export const CLEAR_LNG_NULL_ERROR = 'CLEAR_LNG_NULL_ERROR';
export const CLEAR_LOCATION_NULL_ERROR = 'CLEAR_LOCATION_NULL_ERROR';

export const SET_INPUT_TYPE = 'SET_INPUT_TYPE';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const CLEAR_SEARCH_TERM = 'CLEAR_SEARCH_TERM';

export const SET_SUGGESTIONS = 'SET_SUGGESTIONS';
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS';

export const SET_HIGHLIGHTED_INDEX = 'SET_HIGHLIGHTED_INDEX';

export const SET_LOCATION_LOADING_ON = 'SET_LOCATION_LOADING_ON';
export const SET_LOCATION_LOADING_OFF = 'SET_LOCATION_LOADING_OFF';

export const SET_SUGGESTIONS_LOADING_ON = 'SET_SUGGESTIONS_LOADING_ON';
export const SET_SUGGESTIONS_LOADING_OFF = 'SET_SUGGESTIONS_LOADING_OFF';

export const SET_LOCATION_VALID = 'SET_LOCATION_VALID';
