// src/context/starInputActionTypes.js
export const SET_STAR_NAME = 'SET_STAR_NAME';
export const SET_STAR_HIP = 'SET_STAR_HIP';

export const SET_STAR_RA = 'SET_STAR_RA';
export const SET_STAR_DEC = 'SET_STAR_DEC';
export const SET_STAR_RADEC = 'SET_STAR_RADEC';
export const CLEAR_STAR_RADEC = 'CLEAR_STAR_RADEC';

export const SET_STAR_RA_HOURS = 'SET_STAR_RA_HOURS';
export const SET_STAR_RA_MINUTES = 'SET_STAR_RA_MINUTES';
export const SET_STAR_RA_SECONDS = 'SET_STAR_RA_SECONDS';
export const SET_STAR_RA_HMS = 'SET_STAR_RA_HMS';
export const CLEAR_STAR_RA_HMS = 'CLEAR_STAR_RA_HMS';

export const SET_STAR_DEC_DEGREES = 'SET_STAR_DEC_DEGREES';
export const SET_STAR_DEC_MINUTES = 'SET_STAR_DEC_MINUTES';
export const SET_STAR_DEC_SECONDS = 'SET_STAR_DEC_SECONDS';
export const SET_STAR_DEC_DMS = 'SET_STAR_DEC_DMS';
export const CLEAR_STAR_DEC_DMS = 'CLEAR_STAR_DEC_DMS';

export const SET_STAR_NAME_ERROR = 'SET_STAR_NAME_ERROR';
export const SET_STAR_HIP_ERROR = 'SET_STAR_HIP_ERROR';
export const SET_STAR_RA_ERROR = 'SET_STAR_RA_ERROR';
export const SET_STAR_DEC_ERROR = 'SET_STAR_DEC_ERROR';
export const SET_STAR_ERROR = 'SET_STAR_ERROR';
export const CLEAR_STAR_ERROR = 'CLEAR_STAR_ERROR';

export const SET_STAR_NAME_NULL_ERROR = 'SET_STAR_NAME_NULL_ERROR';
export const SET_STAR_HIP_NULL_ERROR = 'SET_STAR_HIP_NULL_ERROR';
export const SET_STAR_RA_NULL_ERROR = 'SET_STAR_RA_NULL_ERROR';
export const SET_STAR_DEC_NULL_ERROR = 'SET_STAR_DEC_NULL_ERROR';
export const CLEAR_STAR_NAME_NULL_ERROR = 'CLEAR_STAR_NAME_NULL_ERROR';
export const CLEAR_STAR_HIP_NULL_ERROR = 'CLEAR_STAR_HIP_NULL_ERROR';
export const CLEAR_STAR_RA_NULL_ERROR = 'CLEAR_STAR_RA_NULL_ERROR';
export const CLEAR_STAR_DEC_NULL_ERROR = 'CLEAR_STAR_DEC_NULL_ERROR';
export const CLEAR_STAR_NULL_ERROR = 'CLEAR_STAR_NULL_ERROR';

export const SET_INPUT_TYPE = 'SET_INPUT_TYPE';
export const SET_RADEC_FORMAT = 'SET_RADEC_FORMAT';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const CLEAR_SEARCH_TERM = 'CLEAR_SEARCH_TERM';

export const SET_SUGGESTIONS = 'SET_SUGGESTIONS';
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS';

export const SET_HIGHLIGHTED_INDEX = 'SET_HIGHLIGHTED_INDEX';
export const CLEAR_HIGHLIGHTED_INDEX = 'CLEAR_HIGHLIGHTED_INDEX';

export const SET_CACHED_NAMES = 'SET_CACHED_NAMES';

export const SET_STAR_VALID = 'SET_STAR_VALID';
